//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMEINCStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ShippingDetails
    {
        public int ShippingDetails_Id { get; set; }
        public Nullable<int> Member_Id { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<decimal> Amount_Paid { get; set; }
        public string Payment_Type { get; set; }
    
        public virtual Tbl_Members Tbl_Members { get; set; }
    }
}
