//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMEINCStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cart
    {
        public int Cart_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Member_Id { get; set; }
        public Nullable<int> CartStatus_Id { get; set; }
    
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
